# Generated by Django 3.1.3 on 2020-12-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_salesorder_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='products',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='user',
        ),
    ]
