# Generated by Django 3.1.3 on 2020-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20201203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='defaultUser', max_length=50),
            preserve_default=False,
        ),
    ]
